### ISSUE TITLE
2D Mouse brain atlas

### ISSUE THREAD

**Issue by MusculusMus** [ggseg/ggseg#62]
Hi,

Really impressive package to show the brain region!

I have region-specific data from the mouse and try to plot the data to a 2D brain map.  I found the gganatogram R package, this is the closest R package that fits my purpose. However, this package treats the mouse brain as one organ. Your ggseg package seems to focus on human brain, is there any possibility to extend your package to a 2D mouse map?

A heatmap like this will be perfect.

![brain region](https://user-images.githubusercontent.com/37739300/122293339-ea046300-cec4-11eb-9985-64c97420d6f3.png)

**Comment by didacvp** [comment]
Hi. 

 

Sorry for the long delay!
We really appreciate that you like the package.

We have no plans to extend our package to a 2D mouse map in the near future as we have no experience in mouse atlases and we have optimized our package so we can create atlases based on existing human brain parcellations. Because of this, it will not be possible to use our tools for converting your atlas to ggseg. 

 

Since this is a 2D image, you could potentially vectorize this image (e.g. using adobe illustrator), convert it to spatial coordinates and convert it to a “ggseg” object fitted for plotting it in ggplot. This can work, but it would take quite a lot of effort and a lot of manual labor. 

 

Best, 

Didac

 

 

 

 

 

From: Shuai Wang ***@***.***> 
Sent: Wednesday, June 16, 2021 11:06 PM
To: ggseg/ggseg ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ggseg/ggseg] 2D Mouse brain atlas (#62)

 

Hi,

Really impressive package to show the brain region!

I have region-specific data from the mouse and try to plot the data to a 2D brain map. I found the gganatogram R package, this is the closest R package that fits my purpose. However, this package treats the mouse brain as one organ. Your ggseg package seems to focus on human brain, is there any possibility to extend your package to a 2D mouse map?

A heatmap like this will be perfect.

 <https://user-images.githubusercontent.com/37739300/122293339-ea046300-cec4-11eb-9985-64c97420d6f3.png>

**Comment by MusculusMus** [comment]
Hi Didac,

Thanks for your reply.


I can try to vectorize the image by Adobe illustrator, but could you give me some hint about  how to convert it to a spatial coordinates ?


Best,
Shuai
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by didacvp** [comment]
Hi Shuai Wang,

So assuming you have a *png images, you can:
1) convert it to *svg (vector image). Free Software: https://www.vectorizer.io/. Paying software: adobe illustration
2) Convert *svg files to *dxf files. Free software https://cloudconvert.com/svg-to-dxf. Paying, adobe illustrator may do the job
3) Convert *dxf to *shp files. Free software: https://qgis.org/es/site/forusers/download.html  (Inkscape may work as well). Import *dxf file in QGIS (upper left panel). From QGIS the map could be saved as a shape file which seems to be a standard format for geographical data. Save by clincking right-side button in the lower left panel.
4) Open R and upload maps. Conversion to R object (fortify package may help).

This may do the trick. But it is quite an effort to get it working properly so I am unsure whether to recommend you to go this path.

Best, Didac

**Comment by MusculusMus** [comment]
Hi Didac,


Really appreciate your reply, it helps a lot.

I already got the ****.ai (adobe format) file of the brain region which contains path and polygon, then I can try your workflow from step3. I am learning QGIS now and familiar with R, maybe make the job easier to be done.

Thanks.

Best,
Shuai


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
