### ISSUE TITLE
Adding view from bottom and top

### ISSUE THREAD

**Issue by zhengchencai** [ggseg/ggseg#84]
Hello,

Thanks for developing this amazing tool. May I ask if it's possible to plot extra views from the top and bottom like the following (no need to be exactly the same but with bottom and top views)? The default layout is very difficult to see ROIs in the LimBic network. The atlas I use (ggsegSchaefer) seems doesn't have these two originations (df column name is "side"). Could you please guide me a bit to make it possible? I guess I will need to create a new atlas df and add two more views. Thanks a lot

![image](https://user-images.githubusercontent.com/29985544/169837077-ff5aa57d-4c04-49b5-8f82-36c4098e72ab.png)

**Comment by Athanasiamo** [comment]
Hi! I understand that this request comes, but we dont really plan on implementing it. THis is mainly because the atlases are already large in size as they are, and adding more views will make them even larger and hence plotting will be slow and heavy. I appreciate that for some atlases, this means that certain regions might be hidden, but its a balancing act.

What you can do, is make your own atlas, as you mention, with the views you want. And use the general pipeline based on `geom_sf` in ggplot2. This is a freer, less opinionated way of working with atlas data in R than ggseg.

https://ggseg.github.io/ggseg/articles/geom-sf.html

**Comment by zhengchencai** [comment]
Thank you very much. I will follow the tutorial and try to make one.
