### ISSUE TITLE
NAs in legend

### ISSUE THREAD

**Issue by kmeeker1103** [ggseg/ggseg#94]
I used the below code to make a generic template of several ROIs. However, when I run the code 'NA' is introduced into the legend. I can't figure out why this would be since there is no real data and therefore no missing values. Is there a way to resolve so only the ROIs are listed in the legend? Thank you.

someData = data.frame(
  region = c("entorhinal", "fusiform", "inferior temporal", "middle temporal"),
  ROIs = c("entorhinal", "fusiform", "inferior temporal", "middle temporal")
)

  ggseg(.data = someData, mapping = aes(fill = ROIs), position = "stacked",
        colour = "white", size = 0.5, hemisphere = "left") +
  theme_void() +
    theme(legend.position = "bottom",
        legend.text = element_text(size = 9)) +
        guides(fill = guide_legend(ncol = 2)) +
        labs(title = " Jack Meta ROI") +
    theme(plot.title = element_text(hjust = 0.5, face = "bold")) 

![image](https://github.com/ggseg/ggseg/assets/91618823/9a093de0-83f9-4abd-af20-96007361fef6)

**Comment by drmowinckels** [comment]
Hi thanks for using ggseg!

Actually, there is lots of NA here, just not in your data frame. In order to display the entire brain, including regions you do not have in your data, we need to add the remaining regions as NA regions to your plot. Otherwise, you would only see the coloured sections and no grey sections in your plot, i.e. there would be no outline of a brain.

To work around this is a little annoying. I found the best option here is to use scale_fill_manual, and set the fill colours manually. By providing this function with the names of the regions and their colours, you can omit the NA from the legend.

``` r
library(ggseg)
#> Warning: package 'ggseg' was built under R version 4.3.1
library(ggplot2)

someData = data.frame(
  region = c("entorhinal", "fusiform", "inferior temporal", "middle temporal"),
  ROIs = c("entorhinal", "fusiform", "inferior temporal", "middle temporal")
)

ggseg(.data = someData, mapping = aes(fill = ROIs), position = "stacked",
      colour = "white", size = 0.5, hemisphere = "left") +
  theme_void() +
  guides(fill = guide_legend(ncol = 2)) +
  labs(title = " Jack Meta ROI") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "bottom",
    legend.text = element_text(size = 9)
  ) +
  scale_fill_manual(
    breaks = unique(someData$ROIs),
    values = scales::hue_pal()(length(unique(someData$ROIs)))
  )
#> merging atlas and data by 'region'
```

![](https://i.imgur.com/StvGT7Y.png)

<sup>Created on 2023-08-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
